### ISSUE TITLE
Missing column django.db.utils.ProgrammingError: column c.relispartition does not exist

### ISSUE THREAD

**Issue by fizyk** [jazzband/django-redshift-backend#100]
Subject: After upgrading to Djano 4 and django-redshift-backend 3, I get a missing column error:

### Problem
The problem exists on Redshift only, Does not occur on Postgres (we're using Postgres 12) attempting to be redshift though.

#### Procedure to reproduce the problem

"please fill this section"

#### Error logs / results
```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
return self.cursor.execute(sql)
psycopg2.errors.UndefinedColumn: column c.relispartition does not exist
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/application/path/./manage.py", line 23, in <module>
main()
File "/application/path/./manage.py", line 19, in main
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
output = self.handle(*args, **options)
File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 98, in wrapped
res = handle_func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 108, in handle
executor = MigrationExecutor(connection, self.migration_progress_callback)
File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
self.loader = MigrationLoader(self.connection)
File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 58, in __init__
self.build_graph()
File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 235, in build_graph
self.applied_migrations = recorder.applied_migrations()
File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
if self.has_table():
File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 58, in has_table
tables = self.connection.introspection.table_names(cursor)
File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/introspection.py", line 58, in table_names
return get_names(cursor)
File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/introspection.py", line 51, in get_names
for ti in self.get_table_list(cursor)
File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/introspection.py", line 51, in get_table_list
cursor.execute(
File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
return self._execute_with_wrappers(
File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
return executor(sql, params, many, context)
File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
return self.cursor.execute(sql, params)
File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
return self.cursor.execute(sql)
django.db.utils.ProgrammingError: column c.relispartition does not exist

```

- "public link of unexpected result if you have"

#### Expected results
django-redshift-backend will not attempt to query for relispartition column

### Environment info
- OS: Linux
- Python version: 3.9.12
- Django version: 4.0.4
- Django-Redshift-Backend version: 2.1 and 3
- **Redshift**

**Comment by shimizukawa** [comment]
Thanks for your reporting!
@fizyk Please let me know how to reproduce this exception.

**Comment by shimizukawa** [comment]
The `c.relispartition` is used on `DatabaseIntrospection` class for postgres backedn on django. 
https://github.com/django/django/blob/73b4f3f9b3c2c64482c8a1174b3c5ab208d11279/django/db/backends/postgresql/introspection.py#L49-L65

However django-redshift-backend already replaces `DatabaseIntrospection` class to support redshift.
https://github.com/jazzband/django-redshift-backend/blob/57b3d4ac6c987d89878610ac8566d19867ed770f/django_redshift_backend/base.py#L1082-L1084

**Comment by fizyk** [comment]
Hmmm... that's weird. Definitely, I see something that I can improve in ours in your tests. Namely the Postgres version to simulate redshift 🤔 and then the locally used engine...

**Comment by fizyk** [comment]
Will close for now and re-open if this won't be a bug the code I updated dependencies on..
