### ISSUE TITLE
Support adding BinaryFIeld

### ISSUE THREAD

**Issue by shimizukawa** [jazzband/django-redshift-backend#135]
### Problem
- When using BinaryFIeld in django app, migrate command raises a exception.

#### Procedure to reproduce the problem
`example/dj-sql-explorer` raise exception

#### Error logs / results
with logging for `django.db.backends`
```
$ python manage.py migrate explorer 
Operations to perform:
  Apply all migrations: explorer
Running migrations:
  Applying explorer.0001_initial...CREATE TABLE "explorer_query" ("id" integer identity(1, 1) NOT NULL PRIMARY KEY, "title" varchar(255) NOT NULL, "sql" varchar(max) NOT NULL, "description" varchar(max) NOT NULL, "created_at" timestamp with time zone NOT NULL, "last_run_date" timestamp with time zone NOT NULL, "created_by_user_id" integer NULL) ; (params None)
CREATE TABLE "explorer_querylog" ("id" integer identity(1, 1) NOT NULL PRIMARY KEY, "sql" varchar(max) NOT NULL, "is_playground" boolean NOT NULL, "run_at" timestamp with time zone NOT NULL, "query_id" integer NULL, "run_by_user_id" integer NULL) ; (params None)
ALTER TABLE "explorer_query" ADD CONSTRAINT "explorer_query_created_by_user_id_182dd868_fk_auth_user_id" FOREIGN KEY ("created_by_user_id") REFERENCES "auth_user" ("id"); (params ())
ALTER TABLE "explorer_querylog" ADD CONSTRAINT "explorer_querylog_query_id_1635a6b4_fk_explorer_query_id" FOREIGN KEY ("query_id") REFERENCES "explorer_query" ("id"); (params ())
ALTER TABLE "explorer_querylog" ADD CONSTRAINT "explorer_querylog_run_by_user_id_cf26a49f_fk_auth_user_id" FOREIGN KEY ("run_by_user_id") REFERENCES "auth_user" ("id"); (params ())
 OK
  Applying explorer.0002_auto_20150501_1515...ALTER TABLE "explorer_querylog" DROP COLUMN "is_playground" CASCADE; (params ())
 OK
  Applying explorer.0003_query_snapshot...ALTER TABLE "explorer_query" ADD COLUMN "snapshot" boolean DEFAULT %s NOT NULL; (params [False])
 OK
  Applying explorer.0004_querylog_duration...ALTER TABLE "explorer_querylog" ADD COLUMN "duration" double precision NULL; (params [])
 OK
  Applying explorer.0005_auto_20160105_2052... OK
  Applying explorer.0006_query_connection...ALTER TABLE "explorer_query" ADD COLUMN "connection" varchar(128) NULL; (params [])
 OK
  Applying explorer.0007_querylog_connection...ALTER TABLE "explorer_querylog" ADD COLUMN "connection" varchar(128) NULL; (params [])
 OK
  Applying explorer.0008_auto_20190308_1642... OK
  Applying explorer.0009_auto_20201009_0547...ALTER TABLE "explorer_query" ADD COLUMN "connection_tmp" varchar(128) DEFAULT %s NOT NULL; (params [''])
UPDATE explorer_query SET "connection_tmp" = "connection" WHERE "connection" IS NOT NULL; (params [])
ALTER TABLE explorer_query DROP COLUMN "connection" CASCADE; (params [])
ALTER TABLE explorer_query RENAME COLUMN "connection_tmp" TO "connection"; (params [])
ALTER TABLE "explorer_querylog" ADD COLUMN "connection_tmp" varchar(128) DEFAULT %s NOT NULL; (params [''])
UPDATE explorer_querylog SET "connection_tmp" = "connection" WHERE "connection" IS NOT NULL; (params [])
ALTER TABLE explorer_querylog DROP COLUMN "connection" CASCADE; (params [])
ALTER TABLE explorer_querylog RENAME COLUMN "connection_tmp" TO "connection"; (params [])
 OK
  Applying explorer.0010_sql_required... OK
  Applying explorer.0011_query_favorites...CREATE TABLE "explorer_queryfavorite" ("id" integer identity(1, 1) NOT NULL PRIMARY KEY, "query_id" integer NOT NULL, "user_id" integer NOT NULL) ; (params None)
ALTER TABLE "explorer_queryfavorite" ADD CONSTRAINT "explorer_queryfavorite_query_id_1f4e3cf7_fk_explorer_query_id" FOREIGN KEY ("query_id") REFERENCES "explorer_query" ("id"); (params ())
ALTER TABLE "explorer_queryfavorite" ADD CONSTRAINT "explorer_queryfavorite_user_id_5ef2792c_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id"); (params ())
ALTER TABLE "explorer_queryfavorite" ADD CONSTRAINT "explorer_queryfavorite_query_id_user_id_602b82de_uniq" UNIQUE ("query_id", "user_id"); (params ())
 OK
  Applying explorer.0012_alter_queryfavorite_query_alter_queryfavorite_user... OK
  Applying explorer.0013_querylog_error_querylog_success...ALTER TABLE "explorer_querylog" ADD COLUMN "error" varchar(max) NULL; (params [])
ALTER TABLE "explorer_querylog" ADD COLUMN "success" boolean DEFAULT %s NOT NULL; (params [True])
 OK
  Applying explorer.0014_promptlog...CREATE TABLE "explorer_promptlog" ("id" integer identity(1, 1) NOT NULL PRIMARY KEY, "prompt" varchar(max) NOT NULL, "response" varchar(max) NOT NULL, "run_at" timestamp with time zone NOT NULL, "duration" double precision NULL, "model" varchar(128) NOT NULL, "error" varchar(max) NULL, "run_by_user_id" integer NULL) ; (params None)
ALTER TABLE "explorer_promptlog" ADD CONSTRAINT "explorer_promptlog_run_by_user_id_ec301ea7_fk_auth_user_id" FOREIGN KEY ("run_by_user_id") REFERENCES "auth_user" ("id"); (params ())
 OK
  Applying explorer.0015_explorervalue...CREATE TABLE "explorer_explorervalue" ("id" integer identity(1, 1) NOT NULL PRIMARY KEY, "key" varchar(5) NOT NULL, "value" varchar(max) NULL) ; (params None)
 OK
  Applying explorer.0016_alter_explorervalue_key...ALTER TABLE "explorer_explorervalue" ADD CONSTRAINT "explorer_explorervalue_key_91a291b6_uniq" UNIQUE ("key"); (params ())
 OK
  Applying explorer.0017_databaseconnection...CREATE TABLE "explorer_databaseconnection" ("id" integer identity(1, 1) NOT NULL PRIMARY KEY, "alias" varchar(255) NOT NULL UNIQUE, "engine" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "user" varchar(255) NOT NULL, "password" varchar(255) NOT NULL, "host" varchar(255) NOT NULL, "port" varchar(255) NOT NULL) ; (params None)
 OK
  Applying explorer.0018_alter_databaseconnection_host_and_more...ALTER TABLE "explorer_databaseconnection" ADD COLUMN "host_tmp" bytea DEFAULT %s NOT NULL; (params [<psycopg2.extensions.Binary object at 0x7603af3d2220>])
Traceback (most recent call last):
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.FeatureNotSupported: Column "host_tmp" has unsupported type "bytea".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/manage.py", line 22, in <module>
    main()
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 244, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 608, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/workspaces/django-redshift-backend/django_redshift_backend/base.py", line 570, in _alter_field
    self.execute(
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.NotSupportedError: Column "host_tmp" has unsupported type "bytea".
```

#### Expected results
- no exception

### Environment info
- Python version: 3.10.14
- Django version: 3.2.25
- Django-Redshift-Backend version:  3.0.0, master

**Comment by shimizukawa** [comment]
All of the UnitTests passed, but there was an error in the migration of the actual project examples/dj-sql-explorer. I'll fix it.

```
$ python manage.py migrate explorer 
Operations to perform:
  Apply all migrations: explorer
Running migrations:
...
  Applying explorer.0018_alter_databaseconnection_host_and_more...Traceback (most recent call last):
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/manage.py", line 22, in <module>
    main()
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 244, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/workspaces/django-redshift-backend/examples/dj-sql-explorer/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 608, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/workspaces/django-redshift-backend/django_redshift_backend/base.py", line 539, in _alter_field
    fragment, other_actions = self._alter_column_type_sql(
  File "/workspaces/django-redshift-backend/django_redshift_backend/base.py", line 971, in _alter_column_type_sql
    fragment, actions = self._alter_column_with_recreate(
  File "/workspaces/django-redshift-backend/django_redshift_backend/base.py", line 756, in _alter_column_with_recreate
    definition, params = self.column_sql(model, new_field, include_default=True)
  File "/workspaces/django-redshift-backend/django_redshift_backend/base.py", line 192, in column_sql
    definition, params = self._modify_params_for_redshift(definition, params)
  File "/workspaces/django-redshift-backend/django_redshift_backend/base.py", line 215, in _modify_params_for_redshift
    params[i] = p.adapted.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by shimizukawa** [comment]
by https://github.com/jazzband/django-redshift-backend/pull/137 fixes migration of `example/dj-sql-explorer`

forward migration
```
(venv) @shimizukawa ➜ /workspaces/django-redshift-backend/examples/dj-sql-explorer (135-binaryfield-support) $ python manage.py migrate explorer 0018
Operations to perform:
  Target specific migration: 0018_alter_databaseconnection_host_and_more, from explorer
Running migrations:
  Applying explorer.0018_alter_databaseconnection_host_and_more...ALTER TABLE "explorer_databaseconnection" ADD COLUMN "host_tmp" varbyte(255) DEFAULT %s NOT NULL; (params [<django_redshift_backend.psycopg2adapter.RedshiftBinary object at 0x7d87221efd30>])
UPDATE explorer_databaseconnection SET "host_tmp" = "host"::varbyte WHERE "host" IS NOT NULL; (params [])
ALTER TABLE explorer_databaseconnection DROP COLUMN "host" CASCADE; (params [])
ALTER TABLE explorer_databaseconnection RENAME COLUMN "host_tmp" TO "host"; (params [])
ALTER TABLE "explorer_databaseconnection" ADD COLUMN "password_tmp" varbyte(255) DEFAULT %s NOT NULL; (params [<django_redshift_backend.psycopg2adapter.RedshiftBinary object at 0x7d8721d2c810>])
UPDATE explorer_databaseconnection SET "password_tmp" = "password"::varbyte WHERE "password" IS NOT NULL; (params [])
ALTER TABLE explorer_databaseconnection DROP COLUMN "password" CASCADE; (params [])
ALTER TABLE explorer_databaseconnection RENAME COLUMN "password_tmp" TO "password"; (params [])
ALTER TABLE "explorer_databaseconnection" ADD COLUMN "user_tmp" varbyte(255) DEFAULT %s NOT NULL; (params [<django_redshift_backend.psycopg2adapter.RedshiftBinary object at 0x7d8721d2cc20>])
UPDATE explorer_databaseconnection SET "user_tmp" = "user"::varbyte WHERE "user" IS NOT NULL; (params [])
ALTER TABLE explorer_databaseconnection DROP COLUMN "user" CASCADE; (params [])
ALTER TABLE explorer_databaseconnection RENAME COLUMN "user_tmp" TO "user"; (params [])
 OK
```

backward migrattion
```
(venv) @shimizukawa ➜ /workspaces/django-redshift-backend/examples/dj-sql-explorer (135-binaryfield-support) $ python manage.py migrate explorer 0017
Operations to perform:
  Target specific migration: 0017_databaseconnection, from explorer
Running migrations:
  Rendering model states... DONE
  Unapplying explorer.0018_alter_databaseconnection_host_and_more...ALTER TABLE "explorer_databaseconnection" ADD COLUMN "user_tmp" varchar(255) DEFAULT %s NOT NULL; (params [''])
UPDATE explorer_databaseconnection SET "user_tmp" = "user"::varchar WHERE "user" IS NOT NULL; (params [])
ALTER TABLE explorer_databaseconnection DROP COLUMN "user" CASCADE; (params [])
ALTER TABLE explorer_databaseconnection RENAME COLUMN "user_tmp" TO "user"; (params [])
ALTER TABLE "explorer_databaseconnection" ADD COLUMN "password_tmp" varchar(255) DEFAULT %s NOT NULL; (params [''])
UPDATE explorer_databaseconnection SET "password_tmp" = "password"::varchar WHERE "password" IS NOT NULL; (params [])
ALTER TABLE explorer_databaseconnection DROP COLUMN "password" CASCADE; (params [])
ALTER TABLE explorer_databaseconnection RENAME COLUMN "password_tmp" TO "password"; (params [])
ALTER TABLE "explorer_databaseconnection" ADD COLUMN "host_tmp" varchar(255) DEFAULT %s NOT NULL; (params [''])
UPDATE explorer_databaseconnection SET "host_tmp" = "host"::varchar WHERE "host" IS NOT NULL; (params [])
ALTER TABLE explorer_databaseconnection DROP COLUMN "host" CASCADE; (params [])
ALTER TABLE explorer_databaseconnection RENAME COLUMN "host_tmp" TO "host"; (params [])
 OK
```

**Comment by shimizukawa** [comment]
dj-sql-explorer works fine.
![image](https://github.com/user-attachments/assets/7b3c3467-e7c5-4bcc-bc87-0d94eec80682)

**Comment by shimizukawa** [comment]
merged.
