### ISSUE TITLE
Unable to Connect to Redshift due to an Authentication Error from psycopg2

### ISSUE THREAD

**Issue by AM-FE-Schonfeld** [jazzband/django-redshift-backend#146]
Subject: Authentication Method 13 Not Supported

### Problem
- Unable to connect to the DB due to an authentication error; I tried several of the psql authentication "OPTIONS" as well and still could not connect. Was more looking for guidance on here, not sure if this is due to the `django-redshift-backend`, `psycopg2` or actual server authentication requirements. For what it is worth, I am able to use the aws `redshift_connector` package with the same exact credentials just fine

#### Error logs / results
```
Traceback (most recent call last):
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django_redshift_backend\_vendor\django40\db\backends\base\base.py", line 244, in ensure_connection
    self.connect()
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django_redshift_backend\_vendor\django40\db\backends\base\base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django_redshift_backend\_vendor\django40\db\backends\postgresql\base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "MY_DB_HOST.redshift.amazonaws.com" (10.74.4.140), port 5439 failed: authentication method 13 not supported
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\IPython\core\formatters.py", line 221, in catch_format_error
    r = method(self, *args, **kwargs)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\IPython\core\formatters.py", line 706, in __call__
    printer.pretty(obj)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\IPython\lib\pretty.py", line 410, in pretty
    return _repr_pprint(obj, self, cycle)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\IPython\lib\pretty.py", line 778, in _repr_pprint
    output = repr(obj)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django\db\models\query.py", line 374, in __repr__
    data = list(self[: REPR_OUTPUT_SIZE + 1])
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django_redshift_backend\_vendor\django40\db\backends\base\base.py", line 284, in cursor
    return self._cursor()
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django_redshift_backend\_vendor\django40\db\backends\base\base.py", line 260, in _cursor
    self.ensure_connection()
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django_redshift_backend\_vendor\django40\db\backends\base\base.py", line 244, in ensure_connection
    self.connect()
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django_redshift_backend\_vendor\django40\db\backends\base\base.py", line 244, in ensure_connection
    self.connect()
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django_redshift_backend\_vendor\django40\db\backends\base\base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\django_redshift_backend\_vendor\django40\db\backends\postgresql\base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\USERNAME\environments\risk\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "MY_DB_HOST.redshift.amazonaws.com" (10.74.4.140), port 5439 failed: authentication method 13 not supported

```

### Environment info
- OS: Windows 10
- Python version: 3.8
- Django version: 4.2.15
- Django-Redshift-Backend version: 4.1.0

**Comment by shimizukawa** [comment]
It seems that you can connect depending on the version or binary build of psycopg2. Please refer to the following issue.
https://github.com/psycopg/psycopg2/issues/601
